name: CI pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
       DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
       DOCKER_PASSWORD: ${{secrets.DOCKER_ACCESS_TOKEN }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
       
    - name: Build the Docker image
      run: docker build -t ankit021/docker-and-action .
    - name: push to Dockerhub
      run: docker push ankit021/docker-and-action:latest
